import util

class Configurations:
    def __init__(self):
        config = util.LoadConfig('./config.json')

        self.FACES_CLASSES_COUNT = config['FACES_CLASSES_COUNT']
        self.FACENET_MODEL_PATH = config['FACENET_MODEL_PATH']
        self.NN_MODEL_PATH = config['NN_MODEL_PATH']

        # data settings
        self.TRAINING_SET_PATH = config['DATA']['TRAINING_SET_PATH']
        self.VALIDATE_SET_PATH = config['DATA']['VALIDATE_SET_PATH']
        self.COMPRESSED_FACE_IMAGE_DATASET_PATH = config['DATA']['COMPRESSED_FACE_IMAGE_DATASET_PATH']
        self.COMPRESSED_FACE_EMBEDDING_PATH = config['DATA']['COMPRESSED_FACE_EMBEDDING_PATH']

        self.FACE_CLASS_VIDEO_DIRECTORY = config['FACE_CLASS_VIDEO_DIRECTORY']
        self.VIDEO_SAMPLING_FREQUENCY = config['VIDEO_SAMPLING_FREQUENCY']

        # faces classification settings
        self.FACES_CLASSIFICATION_DIRECTORY = config['FACES_CLASSIFICATION']['FACES_CLASSIFICATION_DIRECTORY']
        self.FACES_CLASSIFICATION_OUTPUT = config['FACES_CLASSIFICATION']['FACES_CLASSIFICATION_OUTPUT']
        self.FACES_CLASSIFICATION_RECORD_DIRECTORY = config['FACES_CLASSIFICATION']['FACES_CLASSIFICATION_RECORD_DIRECTORY']
        self.FACES_CLASSIFICATION_NN_DISTANCE_THRESHOLD = config['FACES_CLASSIFICATION']['FACES_CLASSIFICATION_NN_DISTANCE_THRESHOLD']

        self.VERBOSITY = config['VERBOSITY']
        self.DEMO_INPUT_VIDEO_PATH = config['DEMO_INPUT_VIDEO_PATH']


